---
# Playbook for Kali

# Deploy additional tools
- hosts: all
  become: true
  tasks:
    - name: Install Burp Suite
      ansible.builtin.include_role:
        name: iesplin.burp_suite

    - name: Update burpsuite custom facts
      ansible.builtin.blockinfile:
        path: /etc/ansible/facts.d/burpsuite.fact
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ burpsuite_user }}"
        block: |
          [{{ burpsuite_user }}]
          edition={{ burpsuite_edition }}
          licensed=True
      when:
        - burpsuite_edition == "pro"
        - burpsuite_activate

    # Visual Studio Code
    - name: Fetch Microsoft signing key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/keyrings/packages.microsoft.asc
        owner: root
        group: root
        mode: '0644'

    - name: Add Microsoft VS Code repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.asc] https://packages.microsoft.com/repos/code stable main"
        state: present
        filename: vscode

    - name: Install Visual Studio Code
      ansible.builtin.apt:
        name: code
        state: present
        update_cache: true

    # Clone git repos
    - name: Clone git repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "/opt/{{ item.name }}"
        version: "{{ item.version | default('master') }}"
        depth: 1
        force: true
      loop: "{{ git_repos | flatten(levels=1) }}"

    # Miscellaneous tools
    - name: Ensure destination directory exists
      ansible.builtin.file:
        dest: "{{ item.dest | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ misc_downloads }}"

    - name: Download files
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode | default('0644') }}"
      loop: "{{ misc_downloads }}"
