---
# Playbook for Kali

## Deploy tools not in the Kali repositories
- hosts: kali
  become: true
  tasks:
    - name: Install Burp Suite
      ansible.builtin.include_role:
        name: "ansible-role-burpsuite"

    - name: Create .burpsuitepro_licensed after successful Pro install
      ansible.builtin.file:
        path: "{{ kali_user_details.home }}/.burpsuitepro_licensed"
        state: touch
      when: 'burpsuite_product_type == "pro"'

    - name: Install Keystone Engine
      ansible.builtin.include_role:
        name: "ansible-role-keystone-engine"

    - name: Install MS Visual Studio Code
      ansible.builtin.include_role:
        name: "ansible-role-vscode"

    ### Clone projects from git repos ###
    # Various projects that are either not in Kali or are updated more frequently than Kali repos
    - name: Clone git repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "/opt/{{ item.name }}-git"
        version: "{{ item.version | default('master') }}"
        force: true
      loop: "{{ git_repos | flatten(levels=1) }}"

    ### Miscellaneous tools ###
    - name: Ensure destination directory exists
      ansible.builtin.file:
        dest: "{{ item.dest | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ misc_downloads }}"
            
    - name: Download files
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0755"
      loop: "{{ misc_downloads }}"

    ### Sublime-Text ###
    - name: Add Sublime-text apt key
      ansible.builtin.apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name : Add Sublime-text repository
      ansible.builtin.apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        state: present
        filename: sublimetext
        mode: 640

    - name: Install Sublime-text packages
      ansible.builtin.apt:
        pkg: 
          - sublime-text
          - sublime-merge
        state: present
    
    ### Typora ###
    - name: Add Typora apt key
      ansible.builtin.apt_key:
        url: https://typora.io/linux/public-key.asc
        state: present

    - name : Add Typora repository
      ansible.builtin.apt_repository:
        repo: deb https://typora.io/linux ./
        state: present
        filename: typora
        mode: 640

    - name: Install Typora package
      ansible.builtin.apt:
        name: typora
        state: present
    
    ### CyberChef ###
    - name: Creates cyberchef directory
      ansible.builtin.file:
        dest: /var/www/html/cyberchef/
        state: directory
        owner: root
        group: root
        mode: 655

    - name: Download and unarchive CyberChef
      ansible.builtin.unarchive:
        src: https://github.com/gchq/CyberChef/releases/download/v9.37.0/CyberChef_v9.37.0.zip
        dest: /var/www/html/cyberchef/
        remote_src: yes

    - name: Create a symbolic link - CyberChef
      ansible.builtin.file:
        src: /var/www/html/cyberchef/CyberChef_v9.37.0.zip
        dest: /var/www/html/cyberchef.htm
        owner: root
        group: root
        state: link


