---
# Playbook for Kali

## Deploy tools not in the Kali repositories
- hosts: kali
  become: true
  vars_files:
    - config.yml
  roles:
    - ansible-role-burpsuite
    - ansible-role-ghidra
    - ansible-role-keystone-engine
    - ansible-role-vscode
  tasks:
    ### Install Pwntools ###
    - name: Install Pwntools dependencies
      apt:
        name: "{{ pwntools_dep_packages }}"
        state: present
      vars:
        pwntools_dep_packages:
          - build-essential
          - git
          - libffi-dev
          - libssl-dev
          - python3-dev
          - python3-pip
          - python3-setuptools

    - name: Pip install Pwntools
      pip:
        name: "git+https://github.com/Gallopsled/pwntools.git@dev"
        executable: pip3
        state: latest

    ### Clone projects from git repos ###
    # Various projects that are either not in Kali or are updated more frequently than Kali repos
    - name: Clone git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/{{ item.name }}"
        version: "{{ item.version | default('master') }}"
        force: true
      loop: "{{ git_repos | flatten(levels=1) }}"

    ### Miscellaneous tools ###
    - name: Ensure destination directory exists
      file:
        dest: "{{ item.dest | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ misc_downloads }}"
            
    - name: Download files
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode | default(0644) }}"
      loop: "{{ misc_downloads }}"
