---
- name: User choices
  hosts: kali
  vars:
    burpsuite_products_map:
      - { name: Burp Suite Community, alias: community }
      - { name: Burp Suite Professional, alias: pro }

  tasks:

    - name: Check if host config exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "host_vars/{{ ansible_facts['default_ipv4']['address'] }}/vars.yml"
      register: config_yml

    - block:
        - name: Kali user prompt
          ansible.builtin.pause:
            prompt: Enter the username you want to use on kali (default {{ kali_user }})?
          register: _kali_user_choice

        - name: Set kali_user fact
          ansible.builtin.set_fact:
            kali_user: "{{ _kali_user_choice.user_input }}"
          when: '_kali_user_choice.user_input != ""'
      when: not config_yml.stat.exists

    - name: Get user details
      user:
        name: "{{ kali_user }}"
      register: kali_user_details

    - block:
        - name: Burp Suite edition prompt
          ansible.builtin.pause:
            prompt: |
              What Burp Suite product would you like to install?
                {% for p in burpsuite_products_map %}
                {{ loop.index }}. {{ p['name'] }}
                {% endfor %}

              Enter the number for the product
          register: _burpsuite_choice

        - name: Set product type fact
          ansible.builtin.set_fact:
            burpsuite_product_type: "{{ burpsuite_products_map[_burpsuite_choice.user_input|default(omit)|int - 1]['alias'] }}"
      when: 'burpsuite_product_type is undefined'

    - name: Check .burpsuitepro_licensed file
      stat:
        path: "{{ kali_user_details.home }}/.burpsuitepro_licensed"
      register: check_burpsuitepro_licensed
      when: 'burpsuite_product_type == "pro"'

    - block:
        - name: Burp Suite License prompt
          ansible.builtin.pause:
            prompt: "Enter the Burp Suite Pro license key:"
          register: _burpsuite_license

        - name: Set Burp Suite license key fact
          ansible.builtin.set_fact:
            burpsuite_license_key: "{{ _burpsuite_license.user_input }}"
      when: 
        - 'burpsuite_product_type == "pro"'
        - 'not check_burpsuitepro_licensed.stat.exists'

    - name: Create host config directory
      delegate_to: localhost
      file:
        path: "host_vars/{{ ansible_facts['default_ipv4']['address'] }}"
        state: directory

    - name: Save config
      delegate_to: localhost
      ansible.builtin.template:
        src: templates/config/config.yml.j2
        dest: "host_vars/{{ ansible_facts['default_ipv4']['address'] }}/vars.yml"
        mode: 0600

- name: Include Kali packages playbook
  ansible.builtin.import_playbook: kali-packages.yml

- name: Include Kali tools playbook
  ansible.builtin.import_playbook: kali-tools.yml

- name: Include Kali configuration playbook
  ansible.builtin.import_playbook: kali-config.yml

- name: Include Kali personalization playbook
  ansible.builtin.import_playbook: kali-personalize.yml
