---
- name: User choices
  hosts: all
  become: true
  vars:
    burpsuite_editions_map:
      - { name: Burp Suite Community, alias: community }
      - { name: Burp Suite Professional, alias: pro }
  tasks:
    # Ensure user is created. Do not change password if user exists
    - name: Create kali user
      ansible.builtin.user:
        name: "{{ kali_user }}"
        shell: "{{ kali_user_shell | default(default_shell) }}"
        groups: "{{ kali_user_groups | default(default_groups) }}"
        append: true
        create_home: true
        password: "{{ kali_user_password | default('!') }}"
        update_password: on_create
      register: kali_user_details
      vars:
        default_shell: /bin/zsh
        default_groups: sudo

    - name: Set burpsuite_edition
      ansible.builtin.set_fact:
        burpsuite_edition: "{{ ansible_local['burpsuite'][burpsuite_user]['edition'] }}"
      when: ansible_local['burpsuite'][burpsuite_user]['edition'] is defined

    - block:
        - name: Burp Suite edition prompt
          ansible.builtin.pause:
            prompt: |
              Which Burp Suite edition to install?
                {% for p in burpsuite_editions_map %}
                {{ loop.index }}. {{ p['name'] }}
                {% endfor %}

              Enter the number for the product:
          register: _burpsuite_edition_choice

        - name: Set burp_edition
          ansible.builtin.set_fact:
            burpsuite_edition: "{{ burpsuite_editions_map[_burpsuite_edition_choice.user_input|default(omit)|int - 1]['alias'] }}"
      when: ansible_local['burpsuite'][burpsuite_user]['edition'] is undefined

    - name: Set burpsuite_licensed
      ansible.builtin.set_fact:
        burpsuite_licensed: "{{ ansible_local['burpsuite'][burpsuite_user]['licensed'] | default(false) }}"

    - block:
        - name: Burp Suite License prompt
          ansible.builtin.pause:
            prompt: "Enter the Burp Suite Pro license key:"
          register: _burpsuite_license_choice

        - name: Set Burp Suite license key fact
          ansible.builtin.set_fact:
            burpsuite_pro_license_key: "{{ _burpsuite_license_choice.user_input }}"
      when:
        - burpsuite_edition == "pro"
        - not burpsuite_licensed

    - name: Create directory for ansible custom facts
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: true

    - name: Update burpsuite custom facts
      ansible.builtin.blockinfile:
        path: /etc/ansible/facts.d/burpsuite.fact
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ burpsuite_user }}"
        block: |
          [{{ burpsuite_user }}]
          edition={{ burpsuite_edition }}
          licensed={{ burpsuite_licensed }}

- name: Include Kali packages playbook
  ansible.builtin.import_playbook: kali-packages.yml

- name: Include Kali configuration playbook
  ansible.builtin.import_playbook: kali-config.yml

- name: Include Kali tools playbook
  ansible.builtin.import_playbook: kali-tools.yml

- name: Include Kali personalization playbook
  ansible.builtin.import_playbook: kali-personalize.yml
